experiment_name: tgcn_static_corr_only

graph:
  use_corr: true
  use_sector: false
  use_granger: false

evaluation:
  out_dir: "experiments/tgcn_static_corr_only"

include: "configs/templates/models/tgcn_static.yaml"
