experiment_name: gcn

model:
  family: gnn
  type: gcn
  hidden_dim_candidates: [32, 64]
  hidden_dim: 64
  num_layers: 1
  dropout: 0.1

include: "configs/default.yaml"

data:
  target_horizon: 5  # weekly horizon to reduce noise for GCN
